Repository 5Mart-X-EEIT69/5Mart, pull requests merged in 2023-09, with the labels that each got.

#16 add gulp for compiling custom bootstrap
  .gitignore
  SpringEEIT69-5Mart/src/main/resources/gulp/.nvmrc
  SpringEEIT69-5Mart/src/main/resources/gulp/README.md
  SpringEEIT69-5Mart/src/main/resources/gulp/gulpfile.js/envOptions.js
  SpringEEIT69-5Mart/src/main/resources/gulp/gulpfile.js/index.js
  SpringEEIT69-5Mart/src/main/resources/gulp/package-lock.json
  SpringEEIT69-5Mart/src/main/resources/gulp/package.json
  SpringEEIT69-5Mart/src/main/resources/gulp/style/_variables.scss
  SpringEEIT69-5Mart/src/main/resources/gulp/style/bootstrap.scss
  SpringEEIT69-5Mart/src/main/resources/static/assets/vendor/custom-bs/bootstrap.css
  SpringEEIT69-5Mart/src/main/resources/static/assets/vendor/custom-bs/bootstrap.css.map
Labels: enhancement

#17 Merge Feat/template_index_page Change index page file path
  SpringEEIT69-5Mart/.gitignore
  SpringEEIT69-5Mart/src/main/resources/static/templates/index.jsp
Labels: enhancement

#18 Merge fix/unwanted_files Delete unwanted-files
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/test
  SpringEEIT69-5Mart/src/main/resources/static/templates/temp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/test1.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/test2.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/test3.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/testzhang.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/video-api.jsp
Labels: enhancement

#20 add "settings.json" by .vscode
  .vscode/settings.json
Labels: enhancement

#23 Add .vscode "launch.json" & Change pom.xml
  .vscode/launch.json
  .vscode/settings.json
  SpringEEIT69-5Mart/pom.xml
Labels: enhancement

#39 merge add student_coruse_viwer&dashboard into dev
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/student_lms/student_course_viewer.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/student_lms/student_dashboard.jsp
Labels: enhancement

#42 new dev Test/article overview pr into dev
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/HomeController.java
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/1star.png
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/2star.png
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/3star.png
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/4star.png
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/5star.png
  SpringEEIT69-5Mart/src/main/resources/static/assets/images/評論人頭照.jpeg
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/article_overview.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/check.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/evaluate copy.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/evaluate.jsp
Labels: enhancement

#60 fix HomeController Error, delete nouse source
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/HomeController.java
Labels: bug

#64 Feat/video player processing
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/VideoUploadController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/dao/VideoRepository.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/model/Video.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/service/VideoService.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/service/impl/VideoServiceImpl.java
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/Player.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/upload_video.jsp
Labels: enhancement

#65 Update Video.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/model/Video.java
Labels: bug

#67 Update and rename Video.java to Video2.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/model/Video2.java
Labels: bug

#69 Update Video2.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/model/Video2.java
Labels: bug

#71 Jacky0400143 patch 5
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/VideoUploadController.java
Labels: bug

#73 Update HomeController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/HomeController.java
Labels: bug

#74 Update application.properties
  SpringEEIT69-5Mart/src/main/resources/application.properties
Labels: bug

#75 Update StudentController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
Labels: bug

#76 fix StudentController because video api
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
Labels: bug

#77 add Student LMS items
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/CourseViewer/Course_Player.html
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/Development folder/Player.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/Development folder/test.html
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/Development folder/upload_video.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/StudentCommunicate/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/StudentCourse/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/StudentSettings/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/studentIndex.jsp
Labels: enhancement

#78 Feat/devitemsforwang
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/DEV_VideoUploadController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/VideoUploadController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/dao/DEV_VideoRepository.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/model/DEV_Video.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/model/Video2.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/service/DEV_VideoService.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/service/impl/DEV_VideoServiceImpl.java
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/DevelopmentFolder/Player.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/DevelopmentFolder/test.html
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/DevelopmentFolder/upload_video.jsp
Labels: enhancement

#80 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#85 Feat/student lms pages
  SpringEEIT69-5Mart/pom.xml
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/DEV_HomeController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/HomeController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
  SpringEEIT69-5Mart/src/main/resources/static/assets/css/teacherNavBar.css
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/BusinessServices/cartServicePage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/CoursePlayerService/Course_Player.html
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/CourseService/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/DevelopmentFolder/Player.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/DevelopmentFolder/test.html
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/DevelopmentFolder/upload_video.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/NotificationService/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/profileSettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/StudentAccountSettings.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/studentIndex.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/student_course_viewer.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/student_dashboard.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLearningManagementSystem/StudentSettings/Test
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/course-lms.jsp
Labels: enhancement

#86 Update StudentAccountSettings.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/StudentAccountSettings.jsp
Labels: enhancement

#88 Jacky0400143 patch 1
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/RegController.java
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/memberNavBar.jsp
Labels: bug

#94 Feat/studentlms/settings
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/RegController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/controller/StudentController.java
  SpringEEIT69-5Mart/src/main/java/com/ispan/eeit69/service/TeacherPictureService.java
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/DevelopmentFolder/subscriptionSettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/deactivateSettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/paymentSettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/pictureSettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/privacySettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/profileSettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/SettingsService/safetySettingPage.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/StudentLMS/studentIndex.jsp
  SpringEEIT69-5Mart/src/main/webapp/WEB-INF/views/TeacherInformation/TeacherInformationPhoto.jsp
Labels: bug
